// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvJf_IlrJWV19227gpZNtcn7gVrb27Gmc',
    appId: '1:223158262930:web:1a0fc7ef95241acc41da4b',
    messagingSenderId: '223158262930',
    projectId: 'quiz-app-2114f',
    authDomain: 'quiz-app-2114f.firebaseapp.com',
    databaseURL: 'https://quiz-app-2114f-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-2114f.firebasestorage.app',
    measurementId: 'G-Z6XSV3M3K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlM0u5gbePxHAYETmqDHTzS8tlQR9bSrg',
    appId: '1:223158262930:android:6e6d931898c7217c41da4b',
    messagingSenderId: '223158262930',
    projectId: 'quiz-app-2114f',
    databaseURL: 'https://quiz-app-2114f-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-2114f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu2WQdp3gDG95C7_F4jJATXDQcf-bh-Kw',
    appId: '1:223158262930:ios:a0367795039bd64441da4b',
    messagingSenderId: '223158262930',
    projectId: 'quiz-app-2114f',
    databaseURL: 'https://quiz-app-2114f-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-2114f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu2WQdp3gDG95C7_F4jJATXDQcf-bh-Kw',
    appId: '1:223158262930:ios:a0367795039bd64441da4b',
    messagingSenderId: '223158262930',
    projectId: 'quiz-app-2114f',
    databaseURL: 'https://quiz-app-2114f-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-2114f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvJf_IlrJWV19227gpZNtcn7gVrb27Gmc',
    appId: '1:223158262930:web:0d62bdb03722c63941da4b',
    messagingSenderId: '223158262930',
    projectId: 'quiz-app-2114f',
    authDomain: 'quiz-app-2114f.firebaseapp.com',
    databaseURL: 'https://quiz-app-2114f-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-2114f.firebasestorage.app',
    measurementId: 'G-TLQTB8N53J',
  );
}
